---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: tops-cert-mgmt-role-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: cert-mgmt-iam
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "lambda.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags:
      Name: tops-cert-mgmt-role-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: tops-cert-mgmt-policy-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: cert-mgmt-iam
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:us-east-1:*:log-group:/aws/lambda/tops-cert-mgmt-*-v2:*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "s3:GetObject",
              "s3:HeadObject"
            ],
            "Resource": "arn:aws:s3:::tops-cert-bucket-v2/*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "ssm:GetParameter",
              "ssm:GetParameters",
              "ssm:GetParametersByPath"
            ],
            "Resource": "arn:aws:ssm:us-east-1:*:parameter/*"
          }
        ]
      }
    tags:
      Name: tops-cert-mgmt-policy-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: tops-cert-mgmt-policy-v2-attachment
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: cert-mgmt-iam
spec:
  forProvider:
    policyArnRef:
      name: tops-cert-mgmt-policy-v2
    roleRef:
      name: tops-cert-mgmt-role-v2
  providerConfigRef:
    name: default
