---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: tops-udf-cleaner-role-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: udf-cleaner-iam
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "lambda.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags:
      Name: tops-udf-cleaner-role-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: tops-udf-cleaner-policy-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: udf-cleaner-iam
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:us-east-1:*:log-group:/aws/lambda/tops-udf-cleaner-v2:*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "sqs:ReceiveMessage",
              "sqs:DeleteMessage",
              "sqs:GetQueueAttributes",
              "sqs:GetQueueUrl"
            ],
            "Resource": "arn:aws:sqs:us-east-1:*:tops-udf-queue-v2"
          },
          {
            "Effect": "Allow",
            "Action": [
              "dynamodb:GetItem",
              "dynamodb:PutItem",
              "dynamodb:UpdateItem",
              "dynamodb:Scan",
              "dynamodb:Query",
              "dynamodb:DeleteItem"
            ],
            "Resource": "arn:aws:dynamodb:us-east-1:*:table/tops-udf-lab-deployment-state-v2"
          }
        ]
      }
    tags:
      Name: tops-udf-cleaner-policy-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: tops-udf-cleaner-policy-v2-attachment
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: udf-cleaner-iam
spec:
  forProvider:
    policyArnRef:
      name: tops-udf-cleaner-policy-v2
    roleRef:
      name: tops-udf-cleaner-role-v2
  providerConfigRef:
    name: default
