---
# Cleanup Step Function IAM Role
apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata:
  name: tops-cleanup-sfn-role-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: cleanup-iam
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Service": "states.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
          }
        ]
      }
    tags:
      Name: tops-cleanup-sfn-role-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: Policy
metadata:
  name: tops-cleanup-sfn-policy-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: cleanup-iam
spec:
  forProvider:
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Action": [
              "logs:CreateLogDelivery",
              "logs:GetLogDelivery",
              "logs:UpdateLogDelivery",
              "logs:DeleteLogDelivery",
              "logs:ListLogDeliveries",
              "logs:PutResourcePolicy",
              "logs:DescribeResourcePolicies",
              "logs:DescribeLogGroups"
            ],
            "Resource": "*"
          },
          {
            "Effect": "Allow",
            "Action": [
              "lambda:InvokeFunction"
            ],
            "Resource": [
              "arn:aws:lambda:us-east-1:*:function:tops-user-remove-v2",
              "arn:aws:lambda:us-east-1:*:function:tops-ns-remove-v2"
            ]
          }
        ]
      }
    tags:
      Name: tops-cleanup-sfn-policy-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.upbound.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: tops-cleanup-sfn-policy-v2-attachment
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: cleanup-iam
spec:
  forProvider:
    policyArnRef:
      name: tops-cleanup-sfn-policy-v2
    roleRef:
      name: tops-cleanup-sfn-role-v2
  providerConfigRef:
    name: default
