---
# DynamoDB Stream trigger for stream_to_stepfunction Lambda
# Handles both INSERT (provisioning) and REMOVE (cleanup) events
apiVersion: lambda.aws.upbound.io/v1beta1
kind: EventSourceMapping
metadata:
  name: tops-stream-to-sfn-v2-dynamodb-trigger
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: lambda-event-source
spec:
  forProvider:
    region: us-east-1
    batchSize: 1
    maximumRetryAttempts: 2
    bisectBatchOnFunctionError: true
    enabled: true
    startingPosition: LATEST
    functionNameRef:
      name: tops-stream-to-sfn-v2
    eventSourceArn: arn:aws:dynamodb:us-east-1:430171053948:table/tops-udf-lab-deployment-state-v2/stream/2026-02-06T16:13:48.101
    destinationConfig:
      - onFailure:
          - destinationArn: arn:aws:sqs:us-east-1:430171053948:tops-udf-dlq-v2
    filterCriteria:
      - filter:
          - pattern: '{ "eventName": ["INSERT", "REMOVE"] }'
  providerConfigRef:
    name: default
