---
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: tops-fetch-job-config-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: provisioning-lambda
spec:
  forProvider:
    region: us-east-1
    runtime: python3.11
    handler: function.lambda_handler
    timeout: 60
    memorySize: 128
    s3Bucket: tops-lambda-bucket-v2
    s3Key: fetch_job_config_v2.zip
    roleRef:
      name: tops-utility-role-v2
    environment:
      - variables:
          DEPLOYMENT_STATE_BUCKET: tops-deployment-state-v2
          JOB_STATE_TABLE: tops-job-state-v2
    tags:
      Name: tops-fetch-job-config-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: tops-resource-orchestrator-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: provisioning-lambda
spec:
  forProvider:
    region: us-east-1
    runtime: python3.11
    handler: function.lambda_handler
    timeout: 300
    memorySize: 256
    s3Bucket: tops-lambda-bucket-v2
    s3Key: resource_orchestrator_v2.zip
    roleRef:
      name: tops-provisioning-lambda-role-v2
    environment:
      - variables:
          DEPLOYMENT_STATE_BUCKET: tops-deployment-state-v2
          JOB_STATE_TABLE: tops-job-state-v2
          LAMBDA_PREFIX: "tops-"
    tags:
      Name: tops-resource-orchestrator-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: tops-origin-pool-create-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: provisioning-lambda
spec:
  forProvider:
    region: us-east-1
    runtime: python3.11
    handler: function.lambda_handler
    timeout: 60
    memorySize: 128
    s3Bucket: tops-lambda-bucket-v2
    s3Key: origin_pool_create_v2.zip
    roleRef:
      name: tops-utility-role-v2
    environment:
      - variables:
          DEPLOYMENT_STATE_BUCKET: tops-deployment-state-v2
          JOB_STATE_TABLE: tops-job-state-v2
    tags:
      Name: tops-origin-pool-create-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: tops-http-lb-create-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: provisioning-lambda
spec:
  forProvider:
    region: us-east-1
    runtime: python3.11
    handler: function.lambda_handler
    timeout: 60
    memorySize: 128
    s3Bucket: tops-lambda-bucket-v2
    s3Key: http_lb_create_v2.zip
    roleRef:
      name: tops-utility-role-v2
    environment:
      - variables:
          DEPLOYMENT_STATE_BUCKET: tops-deployment-state-v2
          JOB_STATE_TABLE: tops-job-state-v2
    tags:
      Name: tops-http-lb-create-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: tops-waf-policy-create-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: provisioning-lambda
spec:
  forProvider:
    region: us-east-1
    runtime: python3.11
    handler: function.lambda_handler
    timeout: 60
    memorySize: 128
    s3Bucket: tops-lambda-bucket-v2
    s3Key: waf_policy_create_v2.zip
    roleRef:
      name: tops-utility-role-v2
    environment:
      - variables:
          DEPLOYMENT_STATE_BUCKET: tops-deployment-state-v2
          JOB_STATE_TABLE: tops-job-state-v2
    tags:
      Name: tops-waf-policy-create-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Function
metadata:
  name: tops-stream-to-sfn-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: provisioning-lambda
spec:
  forProvider:
    region: us-east-1
    runtime: python3.11
    handler: function.lambda_handler
    timeout: 60
    memorySize: 128
    s3Bucket: tops-lambda-bucket-v2
    s3Key: stream_to_stepfunction_v2.zip
    roleRef:
      name: tops-stream-to-sfn-role-v2
    environment:
      - variables:
          DEPLOYMENT_STATE_TABLE: tops-udf-lab-deployment-state-v2
          LAB_CONFIGURATION_TABLE: tops-udf-lab-config-v2
          STEP_FUNCTION_ARN: arn:aws:states:us-east-1:430171053948:stateMachine:tops-provisioning-workflow-v2
          DEPLOYMENT_STATE_BUCKET: tops-deployment-state-v2
          JOB_STATE_TABLE: tops-job-state-v2
    tags:
      Name: tops-stream-to-sfn-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
