---
# DynamoDB Stream trigger for UDF Worker Lambda
# IMPORTANT: Disabled initially, will enable during cutover
apiVersion: lambda.aws.upbound.io/v1beta1
kind: EventSourceMapping
metadata:
  name: tops-udf-worker-v2-dynamodb-trigger
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: lambda-event-source
spec:
  forProvider:
    region: us-east-1
    batchSize: 1
    enabled: false
    startingPosition: LATEST
    functionNameRef:
      name: tops-udf-worker-v2
    eventSourceArn: arn:aws:dynamodb:us-east-1:430171053948:table/tops-udf-lab-deployment-state-v2/stream/2026-02-06T16:13:48.101
  providerConfigRef:
    name: default
