---
apiVersion: cloudwatchevents.aws.upbound.io/v1beta1
kind: Rule
metadata:
  name: tops-acme-daily-trigger-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: acme-client-eventbridge
spec:
  forProvider:
    description: Triggers ACME Client Lambdas daily
    region: us-east-1
    eventBusName: default
    scheduleExpression: "rate(1 day)"
    state: ENABLED
    tags:
      Name: tops-acme-daily-trigger-v2
      Environment: production
      ManagedBy: crossplane
      Application: tops-core
  providerConfigRef:
    name: default
---
apiVersion: cloudwatchevents.aws.upbound.io/v1beta1
kind: Target
metadata:
  name: tops-acme-mcn-target-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: acme-client-eventbridge
spec:
  forProvider:
    region: us-east-1
    eventBusName: default
    ruleRef:
      name: tops-acme-daily-trigger-v2
    targetId: acme-lambda-mcn-v2
    arn: arn:aws:lambda:us-east-1:430171053948:function:tops-acme-client-mcn-v2
  providerConfigRef:
    name: default
---
apiVersion: cloudwatchevents.aws.upbound.io/v1beta1
kind: Target
metadata:
  name: tops-acme-app-target-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: acme-client-eventbridge
spec:
  forProvider:
    region: us-east-1
    eventBusName: default
    ruleRef:
      name: tops-acme-daily-trigger-v2
    targetId: acme-lambda-app-v2
    arn: arn:aws:lambda:us-east-1:430171053948:function:tops-acme-client-app-v2
  providerConfigRef:
    name: default
---
apiVersion: cloudwatchevents.aws.upbound.io/v1beta1
kind: Target
metadata:
  name: tops-acme-sec-target-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: acme-client-eventbridge
spec:
  forProvider:
    region: us-east-1
    eventBusName: default
    ruleRef:
      name: tops-acme-daily-trigger-v2
    targetId: acme-lambda-sec-v2
    arn: arn:aws:lambda:us-east-1:430171053948:function:tops-acme-client-sec-v2
  providerConfigRef:
    name: default
---
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Permission
metadata:
  name: tops-acme-mcn-eventbridge-permission-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: acme-client-eventbridge
spec:
  forProvider:
    region: us-east-1
    action: lambda:InvokeFunction
    functionNameRef:
      name: tops-acme-client-mcn-v2
    principal: events.amazonaws.com
    sourceArn: arn:aws:events:us-east-1:430171053948:rule/tops-acme-daily-trigger-v2
    statementId: MCN-AllowExecutionFromEventBridge-v2
  providerConfigRef:
    name: default
---
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Permission
metadata:
  name: tops-acme-app-eventbridge-permission-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: acme-client-eventbridge
spec:
  forProvider:
    region: us-east-1
    action: lambda:InvokeFunction
    functionNameRef:
      name: tops-acme-client-app-v2
    principal: events.amazonaws.com
    sourceArn: arn:aws:events:us-east-1:430171053948:rule/tops-acme-daily-trigger-v2
    statementId: App-AllowExecutionFromEventBridge-v2
  providerConfigRef:
    name: default
---
apiVersion: lambda.aws.upbound.io/v1beta1
kind: Permission
metadata:
  name: tops-acme-sec-eventbridge-permission-v2
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: acme-client-eventbridge
spec:
  forProvider:
    region: us-east-1
    action: lambda:InvokeFunction
    functionNameRef:
      name: tops-acme-client-sec-v2
    principal: events.amazonaws.com
    sourceArn: arn:aws:events:us-east-1:430171053948:rule/tops-acme-daily-trigger-v2
    statementId: Sec-AllowExecutionFromEventBridge-v2
  providerConfigRef:
    name: default
