---
# Event Source 1: SQS trigger for UDF Dispatch Lambda
apiVersion: lambda.aws.upbound.io/v1beta1
kind: EventSourceMapping
metadata:
  name: tops-udf-dispatch-v2-sqs-trigger
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: lambda-event-source
spec:
  forProvider:
    region: us-east-1
    batchSize: 1
    enabled: true
    functionNameRef:
      name: tops-udf-dispatch-v2
    eventSourceArnSelector:
      matchLabels:
        app.kubernetes.io/name: tops-core-v2
        app.kubernetes.io/component: sqs-queue
  providerConfigRef:
    name: default
---
# Event Source 2: DynamoDB Stream trigger for UDF Worker Lambda
# IMPORTANT: Disabled initially, will enable during cutover
apiVersion: lambda.aws.upbound.io/v1beta1
kind: EventSourceMapping
metadata:
  name: tops-udf-worker-v2-dynamodb-trigger
  labels:
    app.kubernetes.io/name: tops-core-v2
    app.kubernetes.io/component: lambda-event-source
spec:
  forProvider:
    region: us-east-1
    batchSize: 1
    enabled: false
    startingPosition: LATEST
    functionNameRef:
      name: tops-udf-worker-v2
    eventSourceArnSelector:
      matchLabels:
        app.kubernetes.io/name: tops-core-v2
        app.kubernetes.io/component: dynamodb-lab-deployment-state
  providerConfigRef:
    name: default
